#!/usr/bin/env lua

local function read_file(file)
    local f = io.open(file, "rb")
    local content = f:read("*all")
    f:close()
    return content
end

local function contents_to_array(content)
    local array = {}
    for line in content:gmatch("[^\n]+") do
        table.insert(array, line)
    end
    return array
end

local function extract_repeat_count(line)
    if line:find("x", 1, true) then
        local repeat_amount = line:match("x(%d+)")
        return tonumber(repeat_amount)
    end
end

local function extract_sections(array)
    local sections = {}
    local section_start = 1
    local section_end = 1
    for i, line in ipairs(array) do
        -- Find the start of a section by search for `[` and the line doesn't match `[end]`.
        if line:find("[", 1, true) and not line:find("[end]", 1, true) then
            section_start = i
        elseif line:find("[end]", 1, true) then
            section_end = i
            table.insert(sections, {
                start = section_start,
                end_ = section_end,
            })
        end
    end
    return sections
end

-- The lyrics file to read.
local lyrics = read_file(arg[1])
-- Split the lyrics into an array of lines.
local lines = contents_to_array(lyrics)
-- Extract the sections of the lyrics.
local sections = extract_sections(lines)
-- Iterate over the sections and print the lyrics.
for _, section in ipairs(sections) do
    -- TODO: Remove extra blank lines caused by removing the `[` and `]` lines.
    local lyrics = lines[section.start]:gsub("^%[.-%]$", "")
    for i = section.start + 1, section.end_ do
        -- Add the lyrics, removing any lines starting with `[` and ending with `]`.
        lyrics = lyrics .. "\n" .. lines[i]:gsub("^%[.-%]$", "")
    end
    -- Find the repeat count of the section.
    local repeat_count = extract_repeat_count(lines[section.start])
    if repeat_count then
        -- Print the lyrics `repeat_count` times.
        for i = 1, repeat_count do
            print(lyrics)
        end
    else
        -- Otherwise print the lyrics once.
        print(lyrics)
    end
end
